{
  #arithmetic-expansion ="fg=?";
  #command-substitution ="fg=?";
  #command-substitution-unquoted ="fg=?";
  #process-substitution ="fg=?";
  alias = "fg=#8aadf4";
  arg0 = "fg=#cad3f5";
  assign = "fg=#cad3f5";
  autodirectory = "fg=#f5a97f,italic";
  back-dollar-quoted-argument = "fg=#ed8796";
  back-double-quoted-argument = "fg=#ed8796";
  back-quoted-argument = "fg=#c6a0f6";
  back-quoted-argument-delimiter = "fg=#ed8796";
  back-quoted-argument-unclosed = "fg=#ee99a0";
  builtin = "fg=#8aadf4";
  command = "fg=#8aadf4";
  command-substitution-delimiter = "fg=#cad3f5";
  command-substitution-delimiter-quoted = "fg=#eed49f";
  command-substitution-delimiter-unquoted = "fg=#cad3f5";
  command-substitution-quoted = "fg=#eed49f";
  commandseparator = "fg=#ed8796";
  comment = "fg=#5b6078";
  cursor = "fg=#cad3f5";
  default = "fg=#cad3f5";
  dollar-double-quoted-argument = "fg=#cad3f5";
  dollar-quoted-argument = "fg=#cad3f5";
  dollar-quoted-argument-unclosed = "fg=#ee99a0";
  double-hyphen-option = "fg=#f5a97f";
  double-quoted-argument = "fg=#eed49f";
  double-quoted-argument-unclosed = "fg=#ee99a0";
  function = "fg=#8aadf4";
  global-alias = "fg=#8aadf4";
  globbing = "fg=#cad3f5";
  hashed-command = "fg=#8aadf4";
  history-expansion = "fg=#c6a0f6";
  named-fd = "fg=#cad3f5";
  numeric-fd = "fg=#cad3f5";
  path = "fg=#cad3f5,underline";
  path_pathseparator = "fg=#ed8796,underline";
  path_prefix = "fg=#cad3f5,underline";
  path_prefix_pathseparator = "fg=#ed8796,underline";
  precommand = "fg=#a6da95,italic";
  process-substitution-delimiter = "fg=#cad3f5";
  rc-quote = "fg=#eed49f";
  redirection = "fg=#cad3f5";
  reserved-word = "fg=#a6da95";
  single-hyphen-option = "fg=#f5a97f";
  single-quoted-argument = "fg=#eed49f";
  single-quoted-argument-unclosed = "fg=#ee99a0";
  suffix-alias = "fg=#a6da95";
  unknown-token = "fg=#ee99a0";
}
